export const Emoji = [
    '😄',
    '😁',
    '😆',
    '😅',
    '🤣',
    '🙃',
    '🫠',
    '😉',
    '😊',
    '🥰',
    '😍',
    '🤩',
    '😘',
    '🥲',
    '🤑',
    '🤔',
    '🫡',
    '😑',
    '😏',
    '😬',
    '🤤',
    '🤢',
    '🤮',
    '🥵',
    '🥶',
    '🤯',
    '😎',
    '😕',
    '🥺',
    '😱',
    '😩',
    '😤',
    '😡',
    '🤬',
    '😈',
    '💩',
    '🤡',
    '👻',
    '👽',
    '🙈',
    '🙉',
    '🙊',
    '💔',
    '❤️‍🔥',
    '🧡',
    '🖤',
    '💯',
    '💦',
    '💨',
    '👋',
    '👌',
    '🤌',
    '✌',
    '🫰',
    '🤙',
    '👉',
    '🖕',
    '👍',
    '👎',
    '🤝',
    '🙏',
    '💪',
    '🥃',
    '🍺',
    '🍻',
    '🥂',
    '🏎',
    '🚀',
    '🛸',
    '🌪',
    '🔥',
    '☄',
    '🗿',
    '🔞',
];

export const Stickers = [
    './assets/img/stickers_hasbik/sticker_1.webp',
    './assets/img/stickers_hasbik/sticker_2.webp',
    './assets/img/stickers_hasbik/sticker_3.webp',
    './assets/img/stickers_hasbik/sticker_4.webp',
    './assets/img/stickers_hasbik/sticker_5.webp',
    './assets/img/stickers_hasbik/sticker_6.webp',
    './assets/img/stickers_hasbik/sticker_7.webp',
    './assets/img/stickers_hasbik/sticker_8.webp',
    './assets/img/stickers_hasbik/sticker_9.webp',
    './assets/img/stickers_hasbik/sticker_10.webp',
    './assets/img/stickers_hasbik/sticker_11.webp',
    './assets/img/stickers_hasbik/sticker_12.webp',
    './assets/img/stickers_hasbik/sticker_13.webp',
    './assets/img/stickers_hasbik/sticker_14.webp',
    './assets/img/stickers_hasbik/sticker_15.webp',
    './assets/img/stickers_hasbik/sticker_16.webp',
    './assets/img/stickers_hasbik/sticker_17.webp',
    './assets/img/stickers_hasbik/sticker_18.webp',
    './assets/img/stickers_hasbik/sticker_19.webp',
    './assets/img/stickers_hasbik/sticker_20.webp',
    // './assets/img/stickers_hasbik/sticker_21.webp',
    // './assets/img/stickers_hasbik/sticker_22.webp',
    // './assets/img/stickers_hasbik/sticker_23.webp',
    // './assets/img/stickers_hasbik/sticker_24.webp',
    // './assets/img/stickers_hasbik/sticker_25.webp',
    // './assets/img/stickers_hasbik/sticker_26.webp',
    // './assets/img/stickers_hasbik/sticker_27.webp',
    // './assets/img/stickers_hasbik/sticker_28.webp',
    // './assets/img/stickers_hasbik/sticker_29.webp',
    // './assets/img/stickers_hasbik/sticker_30.webp',

    './assets/img/stickers_dogs/sticker_1.webp',
    './assets/img/stickers_dogs/sticker_2.webp',
    './assets/img/stickers_dogs/sticker_3.webp',
    './assets/img/stickers_dogs/sticker_4.webp',
    './assets/img/stickers_dogs/sticker_5.webp',
    './assets/img/stickers_dogs/sticker_6.webp',
    './assets/img/stickers_dogs/sticker_7.webp',
    './assets/img/stickers_dogs/sticker_8.webp',
    './assets/img/stickers_dogs/sticker_9.webp',
    './assets/img/stickers_dogs/sticker_10.webp',
    './assets/img/stickers_dogs/sticker_11.webp',
    './assets/img/stickers_dogs/sticker_12.webp',
    './assets/img/stickers_dogs/sticker_13.webp',
    './assets/img/stickers_dogs/sticker_14.webp',
    './assets/img/stickers_dogs/sticker_15.webp',
    // './assets/img/stickers_dogs/sticker_16.webp',
    // './assets/img/stickers_dogs/sticker_17.webp',
    // './assets/img/stickers_dogs/sticker_18.webp',
    // './assets/img/stickers_dogs/sticker_19.webp',
    // './assets/img/stickers_dogs/sticker_20.webp',
    // './assets/img/stickers_dogs/sticker_21.webp',
    // './assets/img/stickers_dogs/sticker_22.webp',
    // './assets/img/stickers_dogs/sticker_23.webp',
    // './assets/img/stickers_dogs/sticker_24.webp',
    // './assets/img/stickers_dogs/sticker_25.webp',
    // './assets/img/stickers_dogs/sticker_26.webp',
    // './assets/img/stickers_dogs/sticker_27.webp',
    // './assets/img/stickers_dogs/sticker_28.webp',
    // './assets/img/stickers_dogs/sticker_29.webp',
    // './assets/img/stickers_dogs/sticker_30.webp',

    './assets/img/stickers_cats/sticker_1.webp',
    './assets/img/stickers_cats/sticker_2.webp',
    './assets/img/stickers_cats/sticker_3.webp',
    './assets/img/stickers_cats/sticker_4.webp',
    './assets/img/stickers_cats/sticker_5.webp',
    './assets/img/stickers_cats/sticker_6.webp',
    './assets/img/stickers_cats/sticker_7.webp',
    './assets/img/stickers_cats/sticker_8.webp',
    './assets/img/stickers_cats/sticker_9.webp',
    './assets/img/stickers_cats/sticker_10.webp',
    // './assets/img/stickers_cats/sticker_11.webp',
    // './assets/img/stickers_cats/sticker_12.webp',
    // './assets/img/stickers_cats/sticker_13.webp',
    // './assets/img/stickers_cats/sticker_14.webp',
    // './assets/img/stickers_cats/sticker_15.webp',
    // './assets/img/stickers_cats/sticker_16.webp',
    // './assets/img/stickers_cats/sticker_17.webp',
    // './assets/img/stickers_cats/sticker_18.webp',
    // './assets/img/stickers_cats/sticker_19.webp',

    './assets/img/stickers_duck/sticker_1.webp',
    './assets/img/stickers_duck/sticker_2.webp',
    './assets/img/stickers_duck/sticker_3.webp',
    './assets/img/stickers_duck/sticker_4.webp',
    './assets/img/stickers_duck/sticker_5.webp',
    './assets/img/stickers_duck/sticker_6.webp',
    './assets/img/stickers_duck/sticker_7.webp',
    './assets/img/stickers_duck/sticker_8.webp',
    './assets/img/stickers_duck/sticker_9.webp',
    './assets/img/stickers_duck/sticker_10.webp',
    './assets/img/stickers_duck/sticker_11.webp',
    './assets/img/stickers_duck/sticker_12.webp',
    './assets/img/stickers_duck/sticker_13.webp',
    './assets/img/stickers_duck/sticker_14.webp',
    // './assets/img/stickers_duck/sticker_15.webp',
    // './assets/img/stickers_duck/sticker_16.webp',
    // './assets/img/stickers_duck/sticker_17.webp',
    // './assets/img/stickers_duck/sticker_18.webp',
    // './assets/img/stickers_duck/sticker_19.webp',
    // './assets/img/stickers_duck/sticker_20.webp',
    // './assets/img/stickers_duck/sticker_21.webp',
    // './assets/img/stickers_duck/sticker_22.webp',
    // './assets/img/stickers_duck/sticker_23.webp',
    // './assets/img/stickers_duck/sticker_24.webp',
];

interface Files {
    [key: string]: string;
    pdf: string;
    doc: string;
    docx: string;
    odt: string;
    html: string;
    css: string;
    json: string;
    txt: string;
    file: string;
}

export const Files: Files = {
    pdf: './assets/img/files/pdf.png',
    doc: './assets/img/files/doc.png',
    docx: './assets/img/files/doc.png',
    odt: './assets/img/files/doc.png',
    html: './assets/img/files/html.png',
    css: './assets/img/files/css.png',
    json: './assets/img/files/json.png',
    txt: './assets/img/files/txt.png',
    file: './assets/img/files/file.png',
};
